leftnav:
- identifier: 9c6b954f-7726-fab6-a169-a50e690058e4
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 01bc1582-a428-66aa-0946-d41bd9989915
  name: Readings
  url: /pages/readings
  weight: 20
- identifier: 05fde4f1-28f6-d302-e7f6-e16a24a20bce
  name: Assignments
  url: /pages/assignments
  weight: 30
